title: OuEstCharlie Woof Blog
description: Open, AI-native photo management — built on open standards and privacy
baseurl: "/ouestcharlie"
url: "https://ouestcharlie.github.io"

theme: minima

author: (c) Antoine Hue

logo: /assets/woof_large_850.png
image: /assets/woof_large_850.png

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

sass:
  quiet_deps: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "google*.html"
    values:
      sitemap: false
