title: OuEstCharlie Woof Blog
description: Open, AI-native photo management — built on open standards and privacy
baseurl: ""
url: "https://ouestcharlie.github.io"

theme: minima

author: (c) Antoine Hue

logo: /assets/woof_large_850.png
image: /assets/woof_large_850.png

webmaster_verifications:
  google: QijdD5JeZEHGIIQqeqRfpfqpHdSptNb7PUGA_a6DAkY

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

sass:
  quiet_deps: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  - scope:
      path: "google*.html"
    values:
      sitemap: false
